### ISSUE TITLE
Fix for notification lights getting stuck

### ISSUE THREAD

**Issue by RedKrieg** [vchlum/hue-lights#21]
I sometimes have an issue where many notifications in quick succession will cause the extension to "forget" to unset the notification color on the light.  I was reviewing the Hue API and I believe adding `"alert": "select"` to the parameters you pass to setLights will let you skip the entire "restore lights to previous state" event.  You may need to play with transitiontime instead of using the current value of 0 to make it look good though.

**Comment by vchlum** [comment]
Hi @RedKrieg, `"alert": "select"` is supposed to run notification, but it doesn't work well along with setting a specific color. Not changing the color, It works as expected - it uses the last know color. Changing the color has an unexpected and inconsistent behavior:-(

I am thinking to add a timestamp to the restore state and in case the timestamp is fresh, the restore state would not be overwritten because many notifications are in progress...

**Comment by cm-t** [comment]
That's funny to see this issue right now, I,  yesterday, exprienced this.

 - I opened thunderbird (or telegram, maybe both)
 - I had some notifications
 - light starter to play the notification color
 - I didn't focus on it a lot because it was at that moment I left the room, when I came back later (20min?) the light was still running the notification light instead of the scene it was displaying before.

**Comment by vchlum** [comment]
Issue fixed. Notifications have been redesigned to use queues. The problem shouldn't be possible to happen again.
