### ISSUE TITLE
error message then trying to open settings

### ISSUE THREAD

**Issue by JarelSanders** [vchlum/hue-lights#24]

**Comment by JarelSanders** [comment]
After installing, the setting menu brings up the message 

execution of "gnome-shell-extension-prefs" failed
command not found

**Comment by vchlum** [comment]
Hi @JarelSanders ! The "gnome-shell-extension-prefs" is standard part/ tool in the Gnome, which is not installed. You have not used any settings of any extension since OS installation. Please tell me what distribution do you use, or just Google how to install "gnome-shell-extension-prefs" for your distribution.

**Comment by JarelSanders** [comment]
I installed gnome-shell-extension-prefs and that did the trick!! Thanks!!!!
