### ISSUE TITLE
Is a hue sync box required to sync lights with screen?

### ISSUE THREAD

**Issue by jcklpe** [vchlum/hue-lights#34]
I have installed the app and it is working, but what I am looking to do is sync the screen of my linux media center to my lights. I have done this in the past previously with the amby CLI project but it has not been updated in 4 years and when I recently tried to use it on a reinstalled server environment, it did not work. The README mentions the ability to sync screens to entertainment areas. Is that the same or different than the hue sync box stuff? It appears to be but I do not have a sync box and don't really know what it's for. Reading the docs I would assume these are separate and it would be possible to sync to my linux media servers screen just by using the installed hue-lights gnome extension but I can't figure out how to do that.

**Comment by vchlum** [comment]
I am afraid the entertainment areas support only Philips Hue bulbs. It is a Philips limitation, and I am quite sure it is also a hardware limitation.

You can use the key shortcut 'SUPER+ALT+a' to start the sync selection of a screen. First, you need to set the shortcut in the sync mode sub-menu... after that, the sync selection can be started even in full-screen (with the key shortcut). In order to disable the syncing, you need to go to the menu. There is a lot of combinations of what you can do with entertainment areas and it would be complicated to cover the possibilities with key shortcuts. The shortcut 'SUPER+ALT+a'' was added because of #19.

What do you suggest?

**Comment by jcklpe** [comment]
Thank you for the response. I have some hue bulbs but most of them are gledopto. I have tried using the plugin and it sorta works but is kinda buggy so I guess maybe I'm going to have to pony up for an offbrand sync box eventually.
