### ISSUE TITLE
Option to turn of notifications

### ISSUE THREAD

**Issue by CristianKerr** [vchlum/hue-lights#35]
Hi, thanks for this awesome extension.
When I log in to my computer, sometimes my connection can be messy (vpn connecting and stuff) and the extension spams "connection ... lost" and "connection ... restored".
I would like to be able to turn off notifications for this extension so that I can avoid this. 
Thank you.

**Comment by vchlum** [comment]
I see... OK, I will add an option to disable the notification.

**Comment by vchlum** [comment]
Done. I decided to remove the connection loss/recovery notification.

Since recent update, following "disconnected" label is added to the bridge name if not connected:
![Snímek z 2021-10-20 15-51-11](https://user-images.githubusercontent.com/16756616/138107132-92633296-766a-4d8b-a7a4-f9f4e537b0f5.png)

I think we don't need the notifications at all.

**Comment by vchlum** [comment]
Hi @CristianKerr ! From now on, you can support me and the development of this extension on ko-fi :-D. Caffeine is the necessary ingredient for coding! :-D The sponsor button with the link is on this repository;-)

**Comment by CristianKerr** [comment]
Thanks for letting me know @vchlum I will check it out :)
