### ISSUE TITLE
Standalone, non-gnome version?

### ISSUE THREAD

**Issue by holodrum** [vchlum/hue-lights#36]
Back when I was using ubuntu (using Arch now, btw), this was one of my favorite extensions.

Currently, I'm on qtile, and the one thing I really miss from ubuntu/gnome, is this application.

There are other hue apps out there, but none of them come even close to this one, none of them have scenes imported for example.

Other than wanting to use a tiling window manager, one of my main issues with gnome (besides the amount of bloat) is the fact that on every major update, all of the extensions break. Before switching, it was driving me insane, and I experienced it with this extension as well.

So, I'm wondering, have you thought about creating a standalone version of this, so that both gnome users and other DE/WM users can use it? :)

**Comment by Valachord** [comment]
While I'm obviously sad to hear that (as I love the extension), after reading your answer, it's fully understandable! 

So, what you're really saying is, someone, somehow, needs to make you switch DE/WM?? :thinking: :smile: 

Anyway, here's hoping that someone out there will either recreate your amazing extension, or, come up with some crazy extension translation, wine-like thing, so that gnome extensions can work on other DE/WMs (if that's even possible).
One can only dream :sweat_smile:

**Comment by vchlum** [comment]
You can check [hue-qt](https://github.com/vchlum/hue-qt).... it is still in the early stage. After installing qt6 and compiling, you can try. The basic functionality works. I will close this issue now.
