### ISSUE TITLE
Color changing stopped working

### ISSUE THREAD

**Issue by Gisbitus** [vchlum/hue-lights#45]
The extension was working fine for days, then suddenly I'm unable to change colors for any light. I can turn them on and off fine. Tried all the troubleshooting steps but none worked. I also tried creating a debug log but the command written on the troubleshooting page just hangs and doesn't output anything.

**Comment by vchlum** [comment]
Hi @Gisbitus ! The command should create a file named `hue-lights.log`. Please provide the file. Also, please provide more information... like your distro and gnome version. I did not observe your issue. I will investigate.

**Comment by Gisbitus** [comment]
@vchlum I can run the command and create the log file, but it's empty, unfortunately. What can I do?

**Comment by JordanViknar** [comment]
One of my laptops also has an issue with this extension. Either color changing doesn't work at all, or it's extremely delayed (an entire minute, sometimes 3). The delay also seems to apply to the loading of the settings interface.
This is extremely concerning, nothing in the logs seems to be hinting at the problem. This may be caused by the ["mutter-performance"](https://aur.archlinux.org/packages/mutter-performance) or the ["gnome-shell-performance"](https://aur.archlinux.org/packages/gnome-shell-performance) AUR packages, since I'm using those.
Since I can boot on my BTRFS snapshots with writes in RAM, I can easily try and replace those 2 with the normal packages temporarily to see if that fixes the issue.

The extension works fine on my other laptop though, and it doesn't have the performance packages as it doesn't need them. Perhaps this is a separate problem : if necessary, I can make a different issue for it.

I confirm none of the troubleshooting steps helped.

**Comment by Gisbitus** [comment]
@vchlum yep it's enabled

**Comment by vchlum** [comment]
So only changing color causes issues... Turning on/off and changing scenes works fine... right?
Could you please try to sync your screen with your lights? I suppose the entertainment area should be affected too. It also uses the function `Shell.Screenshot().pick_color()`, which I think causes trouble. 

Could you please try this extension: https://extensions.gnome.org/extension/3396/color-picker/ Are you able to pick the color in a reasonable time? (same function here).

@JordanViknar  I installed both packages on my arch linux test system without noticing the issue.

@Gisbitus What is your linux distribution, please?

**Comment by Gisbitus** [comment]
@vchlum Pop 21.10

**Comment by Gisbitus** [comment]
Closing this issue, the latest update fixed this! Thanks a lot.

**Comment by JordanViknar** [comment]
I'll check if the update fixed this issue (assuming it's the same one) on my end.
