### ISSUE TITLE
Bridge needs Button press all day long

### ISSUE THREAD

**Issue by ChuckNorrison** [vchlum/hue-lights#8]
Hello, thanks for that awesome extension to the hue lights on my ubuntu 20.04 :)

I tested this and it does not remember my "pairing" with the bridge. I always need to reconnect to the Hue Bridge with Button press. 

Iam using Hue essentials on my android connected to that bridge too, should not be a problem or?

**Comment by vchlum** [comment]
Hello @ChuckNorrison , Hue essential should not be a problem.

Seems like a problem in gnome-shell not storing the settings. Please, try to run `dconf-editor` and go to the path `org.gnome.shell.extensions.hue-lights` Do you see your settings here? Especially the key "bridges", which should include the username... (username looks like some random chars) Is it there?

Anyway, try to delete the whole item 'hue-lights' and par it one more time and let me know.

**Comment by ChuckNorrison** [comment]
Hey @vchlum, i tested this on another Ubuntu Machine 20.10 running. No issues so far, even after WLAN disconnect/reconnect i dont need the button press here anymore.

dconf-editor is not installed on both systems.

I already reinstalled several times on my affected system, seems something is wrong with this installation, hard to find.

**Comment by vchlum** [comment]
So both of your machines suffer the issue? I have tested the extension on fresh ubuntu 20.04 and 20.10 without any issue.

Let's try something:

 * Please run `dbus-run-session -- gnome-shell --nested --wayland 2>&1 | grep -C 5 --line-buffered -iE 'hue|gjs' > hue.log` on the affected system. It will open a new gnome-shell. Try to pair the bridge within the newly opened gnome-shell and share the file hue.log. 
 
 * Open https://account.meethue.com/apps Do you see the 'gnome-hue-lights#\<your-hostname\>' items here? Maybe, try to delete all the unused items under "Home network".

 * Please try to run `dconf read /org/gnome/shell/extensions/hue-lights/bridges`. Do you see the username? Please install dconf if not installed (It should be).

**Comment by ChuckNorrison** [comment]
Hey, thanks for your response, here is your log: https://termbin.com/6swvd

**Comment by vchlum** [comment]
Thanks for the log. The pairing is OK.

Do you use the second generation Philips Hue hub (squared shape) or the first generation (round shape)?

To sum things up:
 * you can control the lights but the connection is lost after restarting the machine.
 * The issue is on two of your machines. The first machine runs ubuntu 20.04. The second one runs ubuntu 20.10.
 * since you do not have an account here https://account.meethue.com/apps, you do not use any cloud features (if you have Philips hue account you can use it to log on the page)

Right?

If yes, it must mean the settings were stored successfully but after the restart, it is lost.

The settings use functions from the Gnome shell. It could be a problem outside the extension.

* Please, check for updated system. Run: `sudo apt-get update && sudo apt-get upgrade` . Please check for held back packages too.

* Reboot the machine (for sure).

* run `dconf reset -f /org/gnome/shell/extensions/hue-lights/`

* open hue lights preferences and connect the bridge

* run `dconf dump /org/gnome/shell/extensions/hue-lights/` Do you see the username?

* run `dconf update` (if you see permission error run `sudo dconf update`)

* reboot the machine 
* **do not open hue lights preferences**, just run again `dconf dump /org/gnome/shell/extensions/hue-lights/`  Do you still see the username?

* open hue lights preference and run again `dconf dump /org/gnome/shell/extensions/hue-lights/` Do you see the username now?

Please, tell me the step the issue occurred.

**Comment by ChuckNorrison** [comment]
@vchlum your expectations are right, i dont use hue cloud features, i primary handle my hue system with a hue button and my android hue essentials app which still works great. Iam using a model wiuth model number 2018, looks squared.

Current:
After i enable hue lights from GNOME Extension, only Refresh Menu and Settings are shown. I click on Settings and click the button "Press bridge button and Connect". I press the button on my bridge and the menu gets extended with all the actions. I can use them fine. 

Test:
- My system is updated
- reset done
- read results with (replaced mac here):
```
[/]
bridges={'ecb5fafffe05xxxx': {'ip': '192.168.1.137', 'name': 'Philips hue', 'mac': 'ec:b5:fa:05:xx:xx'}}
```
At this point i observed the pairing does not work. I did it again and it worked. So i disabled it from GNOME Extension and enabled it again. Refresh Menu, i need to pair again. Is this expected?

I repaired it again and will reboot and insert the dumps here

**Comment by vchlum** [comment]
If you disable and enable the extension then the settings should be preserved. No need for a new pairing.

The desired dump should looks like:

`bridges={'ecbxxxxxxxxxxxxx': {'ip': '192.168.1.119', 'name': 'Váša', 'mac': 'ec:b5:x:x:x:x', 'username': 'l0FzyfRZrMWY7pjDDY2qNk4PwuMFzlBek-IBwuOf'}}`

The username must be stored for a limited time and somehow removed/reset. Otherwise, the controlling would not be possible at all.

Also, a complete log could help:
`dbus-run-session -- gnome-shell --nested --wayland &> hue.log`
Within the opened gnome-shell try to connect the bridge and somehow invoke the issue of losing the connection.
The complete log could be more sensitive, please check it before posting. (The Philips hue username is only used on the local network).

The next step would be to add some logging into the extension and install&run it manually. If you agree I will prepare such a version for you.

**Comment by vchlum** [comment]
This issue gets a bit stale. If you would like to continue with debugging please let me know. Since others do not complain about this issue and I am not able to reproduce it, I will close it due to inactivity.
